# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9JAXONE9bG8KqFM47J4hPgiJRnONOK8
"""

import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# --- การตั้งค่าหน้าเว็บ (หมวดที่ 4: Deployed Web Application) ---
st.set_page_config(page_title="Australia Weather Predictor", layout="wide")
st.title("☀️ เครื่องมือพยากรณ์อุณหภูมิสูงสุดรายวัน (Australia)")
st.markdown("""
**คำอธิบายโปรเจค:** แอปนี้ใช้ Machine Learning เพื่อทำนายอุณหภูมิสูงสุด (MaxTemp)
โดยใช้ข้อมูลจาก Bureau of Meteorology, Australia เพื่อช่วยในการวางแผนกิจกรรมกลางแจ้ง
*(จัดทำขึ้นเพื่อวัตถุประสงค์ทางการศึกษา)*
""")

# --- 1. โหลดข้อมูลและการเตรียมข้อมูลเบื้องต้น (หมวดที่ 1 & 2) ---
@st.cache_data
def load_data():
    df = pd.read_csv('weatherAUS.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    # เลือก Features ที่มีนัยสำคัญตามบริบทปัญหาจริง [cite: 15, 21]
    features_list = ['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Humidity3pm', 'Pressure3pm', 'Temp3pm', 'RainToday']
    df = df[features_list].dropna(subset=['MaxTemp'])
    return df

df = load_data()

# --- 2. การวิเคราะห์ข้อมูล (EDA) (หมวดที่ 2) ---
if st.sidebar.checkbox("🔍 แสดงการวิเคราะห์ข้อมูล (EDA)"):
    st.header("📊 สรุปภาพรวมข้อมูล")
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("การกระจายตัวของอุณหภูมิ (Distribution)")
        fig, ax = plt.subplots()
        sns.histplot(df['MaxTemp'], kde=True, color='orange', ax=ax)
        st.pyplot(fig)
    with col2:
        st.subheader("ความสัมพันธ์ระหว่างตัวแปร (Correlation)")
        fig2, ax2 = plt.subplots()
        sns.heatmap(df.select_dtypes(include=[np.number]).corr(), annot=True, cmap='coolwarm', ax=ax2)
        st.pyplot(fig2)

# --- 3. การสร้าง Pipeline (หมวดที่ 2: คะแนนเต็ม 5) ---
# แยกประเภทตัวแปรเพื่อทำ Preprocessing อย่างมีเหตุผล [cite: 21]
num_features = ['MinTemp', 'Rainfall', 'Humidity3pm', 'Pressure3pm', 'Temp3pm']
cat_features = ['Location', 'RainToday']

num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')), # เติมค่าว่างด้วยค่าเฉลี่ย
    ('scaler', StandardScaler()) # ปรับสเกลเพื่อประสิทธิภาพของ Linear Model
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore')) # แปลงตัวหนังสือเป็นตัวเลข
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
])

# แบ่งข้อมูล Training/Testing
X = df.drop('MaxTemp', axis=1)
y = df['MaxTemp']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- 4. การเปรียบเทียบโมเดล (โบนัส 2 คะแนน) ---
@st.cache_resource
def compare_models():
    models = {
        "XGBoost": XGBRegressor(random_state=42),
        "LightGBM": LGBMRegressor(random_state=42, verbose=-1),
        "Linear Regression": LinearRegression()
    }
    results = []
    for name, model in models.items():
        pipe = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', model)])
        pipe.fit(X_train, y_train)
        y_pred = pipe.predict(X_test)
        results.append({
            "Model": name,
            "MAE": mean_absolute_error(y_test, y_pred),
            "RMSE": np.sqrt(mean_squared_error(y_test, y_pred)),
            "R2": r2_score(y_test, y_pred)
        })
    return pd.DataFrame(results).reset_index(drop=True)

if st.sidebar.checkbox("🏆 เปรียบเทียบประสิทธิภาพโมเดล"):
    st.header("🎯 ผลการทดสอบหลายโมเดล")
    res_df = compare_models()
    st.table(res_df.sort_values('MAE'))
    st.info("**วิเคราะห์:** XGBoost มักให้ผลลัพธ์ที่ดีที่สุดเพราะสามารถจัดการข้อมูลสภาพอากาศที่มีความสัมพันธ์แบบ Non-linear ได้ดี")

# --- 5. Hyperparameter Tuning & CV (หมวดที่ 3: คะแนนเต็ม 5) ---
@st.cache_resource
def train_best_model():
    # ใช้ GridSearchCV และ K-Fold Cross Validation ตามเกณฑ์ [cite: 27, 29]
    main_pipe = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', XGBRegressor(random_state=42))])
    param_grid = {
        'regressor__n_estimators': [100, 200],
        'regressor__learning_rate': [0.05, 0.1]
    }
    cv = KFold(n_splits=5, shuffle=True, random_state=42)
    grid_search = GridSearchCV(main_pipe, param_grid, cv=cv, scoring='neg_mean_absolute_error')
    grid_search.fit(X_train, y_train)
    return grid_search

best_model = train_best_model()

# --- 6. ส่วนการทำนายผล (หมวดที่ 4: User Experience) ---
st.header("🔮 ลองทำนายอุณหภูมิ")
with st.container():
    col_in1, col_in2 = st.columns(2)
    with col_in1:
        u_loc = st.selectbox("เลือกสถานที่ (Location)", sorted(df['Location'].unique()))
        u_min = st.number_input("อุณหภูมิต่ำสุด (°C)", value=15.0)
        u_rain = st.selectbox("วันนี้ฝนตกหรือไม่?", ["No", "Yes"])
    with col_in2:
        u_hum = st.slider("ความชื้นเวลา 15:00 (%)", 0, 100, 50)
        u_pres = st.number_input("ความกดอากาศ (hPa)", value=1015.0)
        u_temp3 = st.number_input("อุณหภูมิเวลา 15:00 (°C)", value=20.0)

if st.button("Predict Now"):
    input_data = pd.DataFrame({
        'Location': [u_loc], 'MinTemp': [u_min], 'Rainfall': [0],
        'Humidity3pm': [u_hum], 'Pressure3pm': [u_pres],
        'Temp3pm': [u_temp3], 'RainToday': [u_rain]
    })
    prediction = best_model.predict(input_data)
    st.success(f"### คาดการณ์อุณหภูมิสูงสุด: {prediction[0]:.2f} °C")
    st.warning("**Disclaimer:** ข้อมูลนี้เป็นการพยากรณ์โดยใช้โมเดลคณิตศาสตร์ ไม่ควรใช้เพื่อการตัดสินใจที่สำคัญด้านความปลอดภัย")
